version: '3.8'
services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./app:/source/app
    command: uvicorn app.entrypoint:fastapi_app --host 0.0.0.0 --port 80 --reload
    env_file:
      - .env
    depends_on:
      - redis

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A app.entrypoint:celery_app worker --loglevel=info
    volumes:
      - ./app:/source/app
    env_file:
      - .env
    depends_on:
      - app
      - redis

  flower:
    container_name: flower
    build: .
    command: celery -A app.entrypoint:celery_app flower --port:5555
    ports:
      - "5556:5555"
    volumes:
      - ./app:/source/app
    env_file:
      - .env
    depends_on:
      - app
      - redis
      - celery_worker

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
