version: '3.8'
services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./app:/source/app
    command: uvicorn app.entrypoint:fastapi_app --host 0.0.0.0 --port 80 --reload
    env_file:
      - .env
    depends_on:
      - redis
      - influxdb

  celery_worker:
    container_name: celery_worker
    build: .
    command: celery -A app.entrypoint:celery_app worker --loglevel=info
    volumes:
      - ./app:/source/app
    env_file:
      - .env
    depends_on:
      - app
      - redis

  flower:
    container_name: flower
    build: .
    command: celery -A app.entrypoint:celery_app flower --port:5555
    ports:
      - "5556:5555"
    volumes:
      - ./app:/source/app
    env_file:
      - .env
    depends_on:
      - app
      - redis
      - celery_worker

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"

  influxdb:
    container_name: influxdb
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin-ira-pw
      - DOCKER_INFLUXDB_INIT_ORG=ira-org
      - DOCKER_INFLUXDB_INIT_BUCKET=ira-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ira-super-secret-auth-token

volumes:
  influxdb_data:
    name: influxdb_data