apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  celery-broker-url: "redis://redis:6379/0"
  celery-result-backend: "redis://redis:6379/0"
  redis-host: "redis"
  redis-port: "6379"
  redis-app-db: "1"
  influxdb-url: "http://influxdb:8086"
  influxdb-init-mode: "setup"
  smtp-host: "smtp.office365.com"
  smtp-port: "587"
  auth-enabled: "true"
  gather-kube-metrics: "true"
  postgres-host: "postgres"
  postgres-port: "5432"
  postgres-db: "metrics-api"
  is-external: "false"