apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - args:
            - uvicorn
            - app.main:app
            - --host
            - 0.0.0.0
            - --port
            - "80"
            - --reload
          image: irynanak/monitoring-app
          name: app
          ports:
            - containerPort: 80
              hostPort: 8000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
spec:
  selector:
    app: app
  type: LoadBalancer
  ports:
    - name: "8000"
      port: 8000
      targetPort: 80
      nodePort: 30001
