apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flower
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower
  template:
    metadata:
      labels:
        app: flower
    spec:
      containers:
        - args:
            - celery
            - -A
            - app.celery_worker.celery
            - flower
            - --port:5555
          env:
            - name: CELERY_BROKER_URL
              value: redis://redis:6379/0
            - name: CELERY_RESULT_BACKEND
              value: redis://redis:6379/0
          image: flower
          name: flower
          ports:
            - containerPort: 5555
              hostPort: 5556
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flower
  name: flower
spec:
  ports:
    - name: "5556"
      port: 5556
      targetPort: 5555
  selector:
    app: flower
