apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
        - image: influxdb:2.7.6-alpine
          env:
            - name: DOCKER_INFLUXDB_INIT_MODE
              value: setup
            - name: DOCKER_INFLUXDB_INIT_USERNAME
              value: admin
            - name: DOCKER_INFLUXDB_INIT_PASSWORD
              value: admin-ira-pw
            - name: DOCKER_INFLUXDB_INIT_ORG
              value: ira-org
            - name: DOCKER_INFLUXDB_INIT_BUCKET
              value: ira-bucket
            - name: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
              value: ira-super-secret-auth-token
          name: influxdb
          ports:
            - containerPort: 8086
              hostPort: 8086
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb
spec:
  type: LoadBalancer
  ports:
    - name: "8086"
      port: 8086
      targetPort: 8086
      nodePort: 30002
  selector:
    app: influxdb